"""rename community posts image url to media url

Revision ID: 5f03e59af02c
Revises: 23e01695a91f
Create Date: 2026-05-21 19:44:58.178956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '5f03e59af02c'
down_revision: Union[str, Sequence[str], None] = '23e01695a91f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply the schema changes for this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('community_posts', sa.Column('media_url', sa.String(), nullable=True))
    op.drop_column('community_posts', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the schema changes for this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('community_posts', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('community_posts', 'media_url')
    # ### end Alembic commands ###
