"""add patients and batches tables and update assessments

Revision ID: 6ac40cae8f1a
Revises: 9b03ae2ef4cf
Create Date: 2026-05-08 03:22:10.001259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '6ac40cae8f1a'
down_revision: Union[str, Sequence[str], None] = '9b03ae2ef4cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply the schema changes for this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id')
    )
    op.create_table('batches',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('clinician_id', sa.UUID(), nullable=True),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('total_records', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinician_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('assessments', sa.Column('patient_external_id', sa.String(), nullable=False))
    op.add_column('assessments', sa.Column('batch_id', sa.UUID(), nullable=True))
    op.execute('ALTER TABLE assessments ALTER COLUMN patient_id TYPE UUID USING patient_id::uuid')
    op.create_foreign_key(None, 'assessments', 'batches', ['batch_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'assessments', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the schema changes for this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assessments', type_='foreignkey')
    op.drop_constraint(None, 'assessments', type_='foreignkey')
    op.alter_column('assessments', 'patient_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('assessments', 'batch_id')
    op.drop_column('assessments', 'patient_external_id')
    op.drop_table('batches')
    op.drop_table('patients')
    # ### end Alembic commands ###
