"""add notifications table

Revision ID: 7e93ad18f592
Revises: b9b4a3a1cafe
Create Date: 2026-08-24 10:40:06.056634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '7e93ad18f592'
down_revision: Union[str, Sequence[str], None] = 'b9b4a3a1cafe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply the schema changes for this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.add_column('notifications', sa.Column('actor_user_id', sa.UUID(), nullable=False))
    op.add_column('notifications', sa.Column('post_id', sa.UUID(), nullable=True))
    op.add_column('notifications', sa.Column('conversation_id', sa.UUID(), nullable=True))
    op.alter_column('notifications', 'type',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.create_foreign_key(None, 'notifications', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'notifications', 'users', ['actor_user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'notifications', 'community_posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.drop_column('notifications', 'metadata')
    op.drop_column('notifications', 'title')
    op.drop_column('notifications', 'body')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the schema changes for this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('body', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('notifications', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('notifications', sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.alter_column('notifications', 'type',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('notifications', 'conversation_id')
    op.drop_column('notifications', 'post_id')
    op.drop_column('notifications', 'actor_user_id')
    # ### end Alembic commands ###
