"""create users assessments notifications tables

Revision ID: 9b03ae2ef4cf
Revises: 
Create Date: 2026-05-06 07:14:59.717581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '9b03ae2ef4cf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create the initial application tables for users, assessments, and notifications."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Keep the foreign key to auth.users on the primary key itself so each product profile
    # remains anchored directly to the matching Supabase Auth identity.
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('institution', sa.String(), nullable=True),
    sa.Column('specialisation', sa.String(), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('medical_licence_number', sa.String(), nullable=True),
    sa.Column('licence_document_url', sa.String(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('assessments',
    sa.Column('id', sa.UUID(), nullable=False, server_default=sa.text('gen_random_uuid()')),
    sa.Column('clinician_user_id', sa.UUID(), nullable=True),
    sa.Column('member_user_id', sa.UUID(), nullable=True),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('assessment_role', sa.String(), nullable=False),
    sa.Column('clinical_data', sa.JSON(), nullable=False),
    sa.Column('biopsy_data', sa.JSON(), nullable=True),
    sa.Column('blood_panel_data', sa.JSON(), nullable=True),
    sa.Column('risk_score', sa.Numeric(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('confidence_percent', sa.Integer(), nullable=True),
    sa.Column('agreement', sa.String(), nullable=True),
    sa.Column('models_used', sa.Integer(), nullable=True),
    sa.Column('individual_scores', sa.JSON(), nullable=True),
    sa.Column('clinical_guidance', sa.String(), nullable=True),
    sa.Column('key_risk_drivers', sa.JSON(), nullable=True),
    sa.Column('ood_warning', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['clinician_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['member_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # Preserve assessment history even if linked user accounts are later removed by setting
    # those foreign keys to null rather than cascading the assessment record away.
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Drop the initial application tables in reverse dependency order."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    op.drop_table('assessments')
    op.drop_table('users')
    # ### end Alembic commands ###
